# Assignment

## Brief

Write the Python codes for the following questions.

## Instructions

Paste the answer as Python in the answer code section below each question.

### Question 1

Given the following numpy array:

python
arr = np.array([1, 2, 3, 4, 5])

Write a Python code to multiply each element in the array by 2.

Answer:

In [4]:
import numpy as np

array([ 2,  4,  6,  8, 10])

In [5]:
arr = np.array([1, 2, 3, 4, 5])
arrm = arr * 2

arrm

array([ 2,  4,  6,  8, 10])

### Question 2

Given the following 2D numpy array:

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Write a Python code to select the second row of the array.

Answer:

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arri = arr[1]
arri

array([4, 5, 6])

### Question 4

Given the following 2D numpy array:

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Write a Python code to calculate the sum of all the elements in each row.

Answer:

In [12]:
arrs = arr.sum(axis=1)
arrs

array([ 6, 15, 24])

### Question 5

Given the following 2D numpy array:

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Write a Python code to calculate the average of all the elements.

Answer:

In [14]:
arra = arr.mean()
arra

5.0